### ISSUE TITLE
Missing summarization task in metadata

### ISSUE THREAD

**Issue by djstrong** [MFajcik/benczechmark-leaderboard#2]
Missing summarization task in metadata
```
Traceback (most recent call last):
  File "benczechmark-leaderboard/leaderboard/compile_log_files.py", line 303, in <module>
    main()
  File "benczechmark-leaderboard/leaderboard/compile_log_files.py", line 299, in main
    process_harness_logs(args.input_folder, args.output_file)
  File "benczechmark-leaderboard/leaderboard/compile_log_files.py", line 178, in process_harness_logs
    target_metric = METADATA['tasks'][MAP[taskname]]['metric']
KeyError: 'benczechmark_summarization'
```

**Comment by djstrong** [comment]
Also `benczechmark_czechnews`

**Comment by MFajcik** [comment]
These tasks were  removed due to the excessive contamination.

see e.g., https://github.com/DCGM/lm-evaluation-harness/blob/dc208007defc1468c6362f7ab96253ccffd0a71c/jobs/TASKS.sh#L7

please remove them from your input folder.

I will add some deprecation warning, about their removal. This should be more user-friendly.
