### ISSUE TITLE
KeyError: 'CTKFacts NLI'

### ISSUE THREAD

**Issue by djstrong** [MFajcik/benczechmark-leaderboard#3]
```
Traceback (most recent call last):
  File "benczechmark-leaderboard/leaderboard/compile_log_files.py", line 303, in <module>
    main()
  File "benczechmark-leaderboard/leaderboard/compile_log_files.py", line 299, in main
    process_harness_logs(args.input_folder, args.output_file)
  File "benczechmark-leaderboard/leaderboard/compile_log_files.py", line 270, in process_harness_logs
    'n-shot': all_harness_results['CTKFacts NLI']['n-shot']['ctkfacts_0']
KeyError: 'CTKFacts NLI'
```

**Comment by djstrong** [comment]
It is my mistake.
